In [1]:
%pip install pandas numpy sqlalchemy mysql-connector-python pymysql

Requirement already satisfied: pandas in c:\users\nagis\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\nagis\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: sqlalchemy in c:\users\nagis\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: mysql-connector-python in c:\users\nagis\anaconda3\lib\site-packages (9.7.0)
Requirement already satisfied: pymysql in c:\users\nagis\anaconda3\lib\site-packages (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nagis\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nagis\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nagis\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet>=1 in c:\users\nagis\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\nagis\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\nagis\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [39]:
import os
import re
import numpy as np
import pandas as pd

from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully.")

Libraries imported successfully.

In [37]:
current_folder = os.getcwd()

print("Current folder:")
print(current_folder)

print("\nFiles available:")
for file in os.listdir(current_folder):
    print(file)

Current folder:
C:\Users\nagis\SocialIQ project

Files available:
.ipynb_checkpoints
bengaluru_civic_complaints.csv
citizen_complaints.csv.csv
cleaned_csv_files
dataset_summary_before_cleaning.csv
emergency_detection.csv
enterprise_department_priority.csv
Government_Project_SQL_Implementation.ipynb
government_schemes_lookup.csv
government_sentiment.csv
harmful_content.csv
manual_health_education.csv

In [38]:
file_paths = {
    "bengaluru_civic_complaints": "bengaluru_civic_complaints.csv",
    "citizen_complaints": "citizen_complaints.csv.csv",
    "emergency_detection": "emergency_detection.csv",
    "enterprise_department_priority": "enterprise_department_priority.csv",
    "government_schemes_lookup": "government_schemes_lookup.csv",
    "government_sentiment": "government_sentiment.csv",
    "harmful_content": "harmful_content.csv",
    "manual_health_education": "manual_health_education.csv"
}

print("CSV file mapping created.")

CSV file mapping created.

In [5]:
missing_files = []

for table_name, file_path in file_paths.items():
    if not os.path.exists(file_path):
        missing_files.append(file_path)

if missing_files:
    print("The following files are missing:")
    for file in missing_files:
        print(file)
else:
    print("All CSV files are available.")

All CSV files are available.

In [6]:
dataframes = {}

for table_name, file_path in file_paths.items():
    try:
        df = pd.read_csv(
            file_path,
            low_memory=False,
            encoding="utf-8"
        )

        dataframes[table_name] = df

        print(
            f"{table_name}: "
            f"{df.shape[0]:,} rows and {df.shape[1]} columns"
        )

    except UnicodeDecodeError:
        df = pd.read_csv(
            file_path,
            low_memory=False,
            encoding="latin-1"
        )

        dataframes[table_name] = df

        print(
            f"{table_name}: "
            f"{df.shape[0]:,} rows and {df.shape[1]} columns "
            f"loaded using latin-1 encoding"
        )

bengaluru_civic_complaints: 16,073 rows and 22 columns
citizen_complaints: 10,204 rows and 5 columns
emergency_detection: 7,613 rows and 5 columns
enterprise_department_priority: 100,000 rows and 18 columns
government_schemes_lookup: 3,400 rows and 11 columns
government_sentiment: 60,201 rows and 10 columns
harmful_content: 5,852 rows and 5 columns
manual_health_education: 100 rows and 5 columns

In [7]:
for table_name, df in dataframes.items():
    print("\n" + "=" * 100)
    print(f"TABLE: {table_name}")
    print("=" * 100)

    display(df.head())

====================================================================================================
TABLE: bengaluru_civic_complaints
====================================================================================================

,created_at,ward_id,title,description,sub_category_id,civic_agency_id,location,address,latitude,longitude,ward_title,category_id,category_title,sub_category_title,civic_agency_title,complaint_status_title,comment_count,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,01-01-2019 06:33,22.0,Govt Road is encroached with knowledge of offi...,Govt Road is encroached by Private buildings i...,162,10,"9Th Cross St, Hanumanthappa Layout, Sultanpaly...",Opposite S M Food Palace,13.0318055,77.6054367,Vishwanath Nagenahalli,382,Community Infrastructure and Services,Government Land/Property Encroachment,BBMP,Resolved,6,NaN,NaN,NaN,NaN,NaN
1,01-01-2019 09:59,27.0,S,Money menace is a huge problem with residents ...,42,NaN,"2, 1St Cross Rd, Chikka Banaswadi, Ombr Layout...",NaN,13.0065056,77.6444845,Banasavadi,9,Others,Others,NaN,Open,0,NaN,NaN,NaN,NaN,NaN
2,01-01-2019 12:57,17.0,Showing old owner name in online property tax ...,My property SAS base app no 1600800634 New Pid...,148,10,"No.18 19Th Cross, 19, 19Th Cross, Muthyala Nag...",J P Park,13.0386344,77.551505,J P Park,1,Certificates,Property Tax,BBMP,Resolved,1,NaN,NaN,NaN,NaN,NaN
3,01-01-2019 13:09,161.0,Extremely dangerous BTP barrier in the middle ...,Extremely dangerous BTP barrier in the middle ...,67,10,"Anjaneya Nagar, Ittamadu, Banashankari 3Rd Sta...",NaN,12.9268712,77.5447143,Hosakerehalli,15,"Mobility - Roads, Footpaths and Infrastructure",Tarring Or Asphalting Of Existing Road,BBMP,Resolved,2,NaN,NaN,NaN,NaN,NaN
4,01-01-2019 14:41,176.0,No water supply,Lat few days there is no proper water supply i...,182,2,"27Th Main Rd, Btm 2Nd Stage, Kuvempu Nagar, St...",27th main btm 2nd stage,12.9139053,77.6142494,BTM Layout,23,Water Supply and Services,Regular Water Supply,BWSSB,Open,0,NaN,NaN,NaN,NaN,NaN

====================================================================================================
TABLE: citizen_complaints
====================================================================================================

,tweet_id,tweet_text,c_and_g,category,organization
0,7.193312e+17,1 strong punishmnt cn prevent a lot of crimes ...,0.0,NaN,DelhiPolice
1,7.193329e+17,My PERSONAL view- Father should go to jail too...,0.0,NaN,DelhiPolice
2,7.193385e+17,The minor was challand thrice last yr.But WHY ...,1.0,MINOR,dtptraffic
3,7.193464e+17,@dtptraffic reckless driving by underage kids ...,1.0,MINOR,dtptraffic
4,7.193524e+17,@RailMinIndia Request to run a unresrvd expres...,1.0,suggestion,RailMinIndia

====================================================================================================
TABLE: emergency_detection
====================================================================================================

,id,keyword,location,text,target
0,1,NaN,NaN,Our Deeds are the Reason of this #earthquake M...,1
1,4,NaN,NaN,Forest fire near La Ronge Sask. Canada,1
2,5,NaN,NaN,All residents asked to 'shelter in place' are ...,1
3,6,NaN,NaN,"13,000 people receive #wildfires evacuation or...",1
4,7,NaN,NaN,Just got sent this photo from Ruby #Alaska as ...,1

====================================================================================================
TABLE: enterprise_department_priority
====================================================================================================

,interaction_id,citizen_id,timestamp,channel,department,scheme_name,priority,state,language,sentiment_score,resolution_time_hrs,reopen_count,escalated,satisfaction_rating,cost_to_resolve_inr,complexity_index,sentiment_label,interaction_summary
0,INT-2026-0000001,CIT-221958,01-01-2025 00:00,Social Media (X/Twitter),Ministry of Railways,PM-KISAN,Medium,West Bengal,Kannada,-0.4570,16.23,0,0,1,424.06,8.22,Negative,Issue reported regarding benefit transfer fail...
1,INT-2026-0000002,CIT-771155,01-01-2025 00:05,IVR Helpline,Ministry of Railways,Ayushman Bharat,Medium,West Bengal,English,0.4782,4.50,0,0,5,502.87,7.21,Positive,Inquiry on application status for Ayushman Bha...
2,INT-2026-0000003,CIT-231932,01-01-2025 00:10,Public Grievance Portal (CPGRAMS),Ministry of Housing & Urban Affairs,Ayushman Bharat,Low,Madhya Pradesh,English,0.2100,20.06,1,0,4,489.01,9.90,Positive,Grievance regarding slow processing time and d...
3,INT-2026-0000004,CIT-465838,01-01-2025 00:15,Social Media (X/Twitter),Ministry of Rural Development,Direct Benefit Transfer (DBT),Medium,Uttar Pradesh,Bengali,-0.8239,34.13,3,0,4,192.67,9.80,Negative,Positive feedback submitted for prompt service...
4,INT-2026-0000005,CIT-359178,01-01-2025 00:20,Mobile Application,Ministry of Consumer Affairs,PM Garib Kalyan Anna Yojana,Urgent,Rajasthan,Hindi,-0.8186,36.29,0,0,5,723.86,1.85,Negative,Technical error encountered on digital platfor...

====================================================================================================
TABLE: government_schemes_lookup
====================================================================================================

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,Unnamed: 9,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...",NaN,"Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,NaN,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,NaN,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,NaN,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,NaN,"Social Welfare, Financial Assistance, Deceased..."

====================================================================================================
TABLE: government_sentiment
====================================================================================================

,source_type,record_id,text_content,sentiment,user_or_category,organization,complaint_and_grievance_flag,timestamp,likes,retweets
0,SocialMedia,8379,“Debat@8”. Is Indian narrative against Pakista...,Positive,abasitpak1,IncomeTaxIndia,0,2023-03-10 03:53:21+00:00,27,4
1,SocialMedia,24256,🇮🇳@DrSJaishankar 🇮🇳\nThe few people will be re...,Negative,AJITKUM45682715,MEAIndia,1,2023-01-09 10:15:06+00:00,0,0
2,SocialMedia,43976,Why is the Indian media obsessed with Pakistan...,Positive,maaidahkaleem,MEAIndia,0,2022-10-28 14:45:27+00:00,1,0
3,SocialMedia,41923,@HananyaNaftali @RishiSunak All politics...Win...,Positive,ktantp,dtptraffic,0,2022-11-04 03:40:08+00:00,0,0
4,SocialMedia,29337,What an inspiration! This is what Indian polit...,Positive,annu_itty,IncomeTaxIndia,0,2022-12-16 07:59:01+00:00,1,0

====================================================================================================
TABLE: harmful_content
====================================================================================================

,text_id,text,task_1,task_2,task_3
0,hasoc_en_1,#DhoniKeepsTheGlove | WATCH: Sports Minister K...,NOT,NONE,NONE
1,hasoc_en_2,@politico No. We should remember very clearly ...,HOF,HATE,TIN
2,hasoc_en_3,@cricketworldcup Guess who would be the winner...,NOT,NONE,NONE
3,hasoc_en_4,Corbyn is too politically intellectual for #Bo...,NOT,NONE,NONE
4,hasoc_en_5,All the best to #TeamIndia for another swimmin...,NOT,NONE,NONE

====================================================================================================
TABLE: manual_health_education
====================================================================================================

,manual_id,text,complaint_reason,department,feedback_category
0,H001,The Primary Health Centre in our village has b...,Health,Ministry of Health & Family Welfare,Complaint
1,H002,Waited 4 hours at the government hospital OPD ...,Health,Ministry of Health & Family Welfare,Complaint
2,H003,@HealthMinIndia Why are ASHA workers not visit...,Health,Ministry of Health & Family Welfare,Complaint
3,H004,No ambulance available when my father had ches...,Health,Ministry of Health & Family Welfare,Complaint
4,H005,The maternity ward at our district hospital do...,Health,Ministry of Health & Family Welfare,Complaint

In [8]:
for table_name, df in dataframes.items():
    print("\n" + "=" * 100)
    print(f"INFORMATION: {table_name}")
    print("=" * 100)

    print(df.info())

====================================================================================================
INFORMATION: bengaluru_civic_complaints
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16073 entries, 0 to 16072
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   created_at              16073 non-null  object
 1   ward_id                 16072 non-null  float64
 2   title                   16071 non-null  object
 3   description             16071 non-null  object
 4   sub_category_id         16071 non-null  object
 5   civic_agency_id         15453 non-null  object
 6   location                16070 non-null  object
 7   address                 8881 non-null   object
 8   latitude                16070 non-null  object
 9   longitude               16070 non-null  object
 10  ward_title              16039 non-null  object
 11  category_id             16038 non-null  object
 12  category_title          16039 non-null  object
 13  sub_category_title      16053 non-null  object
 14  civic_agency_title      15416 non-null  object
 15  complaint_status_title  16070 non-null  object
 16  comment_count           16069 non-null  object
 17  Unnamed: 17             4 non-null      object
 18  Unnamed: 18             2 non-null      object
 19  Unnamed: 19             1 non-null      object
 20  Unnamed: 20             1 non-null      object
 21  Unnamed: 21             1 non-null      float64
dtypes: float64(2), object(20)
memory usage: 2.7+ MB
None

====================================================================================================
INFORMATION: citizen_complaints
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10204 entries, 0 to 10203
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tweet_id      9927 non-null   float64
 1   tweet_text    10201 non-null  object
 2   c_and_g       6781 non-null   float64
 3   category      8428 non-null   object
 4   organization  9134 non-null   object
dtypes: float64(2), object(3)
memory usage: 398.7+ KB
None

====================================================================================================
INFORMATION: emergency_detection
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7613 entries, 0 to 7612
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        7613 non-null   int64
 1   keyword   7552 non-null   object
 2   location  5080 non-null   object
 3   text      7613 non-null   object
 4   target    7613 non-null   int64
dtypes: int64(2), object(3)
memory usage: 297.5+ KB
None

====================================================================================================
INFORMATION: enterprise_department_priority
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   interaction_id       100000 non-null  object
 1   citizen_id           100000 non-null  object
 2   timestamp            100000 non-null  object
 3   channel              100000 non-null  object
 4   department           100000 non-null  object
 5   scheme_name          94845 non-null   object
 6   priority             100000 non-null  object
 7   state                100000 non-null  object
 8   language             100000 non-null  object
 9   sentiment_score      100000 non-null  float64
 10  resolution_time_hrs  100000 non-null  float64
 11  reopen_count         100000 non-null  int64
 12  escalated            100000 non-null  int64
 13  satisfaction_rating  100000 non-null  int64
 14  cost_to_resolve_inr  100000 non-null  float64
 15  complexity_index     100000 non-null  float64
 16  sentiment_label      100000 non-null  object
 17  interaction_summary  100000 non-null  object
dtypes: float64(4), int64(3), object(11)
memory usage: 13.7+ MB
None

====================================================================================================
INFORMATION: government_schemes_lookup
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3400 entries, 0 to 3399
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   scheme_name     3400 non-null   object
 1   slug            3400 non-null   object
 2   details         3400 non-null   object
 3   benefits        3400 non-null   object
 4   eligibility     3400 non-null   object
 5   application     3398 non-null   object
 6   documents       3389 non-null   object
 7   level           3400 non-null   object
 8   schemeCategory  3400 non-null   object
 9   Unnamed: 9      0 non-null      float64
 10  tags            3371 non-null   object
dtypes: float64(1), object(10)
memory usage: 292.3+ KB
None

====================================================================================================
INFORMATION: government_sentiment
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60201 entries, 0 to 60200
Data columns (total 10 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   source_type                   60201 non-null  object
 1   record_id                     60201 non-null  object
 2   text_content                  60201 non-null  object
 3   sentiment                     60201 non-null  object
 4   user_or_category              60201 non-null  object
 5   organization                  60201 non-null  object
 6   complaint_and_grievance_flag  60201 non-null  int64
 7   timestamp                     60201 non-null  object
 8   likes                         60201 non-null  int64
 9   retweets                      60201 non-null  int64
dtypes: int64(3), object(7)
memory usage: 4.6+ MB
None

====================================================================================================
INFORMATION: harmful_content
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5852 entries, 0 to 5851
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   text_id  5852 non-null   object
 1   text     5852 non-null   object
 2   task_1   5852 non-null   object
 3   task_2   5852 non-null   object
 4   task_3   5852 non-null   object
dtypes: object(5)
memory usage: 228.7+ KB
None

====================================================================================================
INFORMATION: manual_health_education
====================================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   manual_id          100 non-null    object
 1   text               100 non-null    object
 2   complaint_reason   100 non-null    object
 3   department         100 non-null    object
 4   feedback_category  100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB
None

In [9]:
summary_rows = []

for table_name, df in dataframes.items():
    summary_rows.append({
        "table_name": table_name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_values": int(df.isna().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum())
    })

dataset_summary = pd.DataFrame(summary_rows)

dataset_summary

,table_name,rows,columns,missing_values,duplicate_rows
0,bengaluru_civic_complaints,16073,22,88971,33
1,citizen_complaints,10204,5,6549,8
2,emergency_detection,7613,5,2594,0
3,enterprise_department_priority,100000,18,5155,0
4,government_schemes_lookup,3400,11,3442,3
5,government_sentiment,60201,10,0,0
6,harmful_content,5852,5,0,0
7,manual_health_education,100,5,0,0

In [10]:
dataset_summary.to_csv(
    "dataset_summary_before_cleaning.csv",
    index=False
)

print("Summary saved.")

Summary saved.

In [11]:
def clean_column_name(column_name):
    column_name = str(column_name).strip().lower()

    column_name = re.sub(
        r"[^a-zA-Z0-9_]+",
        "_",
        column_name
    )

    column_name = re.sub(
        r"_+",
        "_",
        column_name
    )

    column_name = column_name.strip("_")

    if column_name and column_name[0].isdigit():
        column_name = "col_" + column_name

    return column_name

In [12]:
for table_name, df in dataframes.items():
    df.columns = [
        clean_column_name(column)
        for column in df.columns
    ]

    dataframes[table_name] = df

print("Column names cleaned successfully.")

Column names cleaned successfully.

In [13]:
for table_name, df in dataframes.items():

    unwanted_columns = [
        column
        for column in df.columns
        if column.lower().startswith("unnamed")
    ]

    if unwanted_columns:
        print(
            f"Removing from {table_name}: "
            f"{unwanted_columns}"
        )

        df = df.drop(columns=unwanted_columns)

    dataframes[table_name] = df

Removing from bengaluru_civic_complaints: ['unnamed_17', 'unnamed_18', 'unnamed_19', 'unnamed_20', 'unnamed_21']
Removing from government_schemes_lookup: ['unnamed_9']

In [14]:
for table_name, df in dataframes.items():

    original_shape = df.shape

    df = df.dropna(axis=0, how="all")
    df = df.dropna(axis=1, how="all")

    dataframes[table_name] = df

    print(
        f"{table_name}: "
        f"{original_shape} → {df.shape}"
    )

bengaluru_civic_complaints: (16073, 17) → (16073, 17)
citizen_complaints: (10204, 5) → (10204, 5)
emergency_detection: (7613, 5) → (7613, 5)
enterprise_department_priority: (100000, 18) → (100000, 18)
government_schemes_lookup: (3400, 10) → (3400, 10)
government_sentiment: (60201, 10) → (60201, 10)
harmful_content: (5852, 5) → (5852, 5)
manual_health_education: (100, 5) → (100, 5)

In [15]:
for table_name, df in dataframes.items():

    text_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for column in text_columns:
        df[column] = (
            df[column]
            .astype("string")
            .str.strip()
        )

    dataframes[table_name] = df

print("Extra spaces removed.")

Extra spaces removed.

In [16]:
invalid_values = [
    "",
    " ",
    "null",
    "NULL",
    "none",
    "None",
    "nan",
    "NaN",
    "N/A",
    "NA",
    "not available",
    "Not Available"
]

for table_name, df in dataframes.items():

    df = df.replace(invalid_values, pd.NA)

    dataframes[table_name] = df

print("Invalid empty values converted to null.")

Invalid empty values converted to null.

In [17]:
for table_name, df in dataframes.items():

    duplicate_count = df.duplicated().sum()

    df = df.drop_duplicates().reset_index(drop=True)

    dataframes[table_name] = df

    print(
        f"{table_name}: "
        f"{duplicate_count:,} duplicate rows removed"
    )

bengaluru_civic_complaints: 33 duplicate rows removed
citizen_complaints: 8 duplicate rows removed
emergency_detection: 0 duplicate rows removed
enterprise_department_priority: 0 duplicate rows removed
government_schemes_lookup: 3 duplicate rows removed
government_sentiment: 0 duplicate rows removed
harmful_content: 0 duplicate rows removed
manual_health_education: 0 duplicate rows removed

In [18]:
for table_name, df in dataframes.items():

    if "sql_row_id" in df.columns:
        df = df.drop(columns=["sql_row_id"])

    df.insert(
        0,
        "sql_row_id",
        range(1, len(df) + 1)
    )

    dataframes[table_name] = df

print("Unique SQL row IDs added.")

Unique SQL row IDs added.

In [19]:
for table_name, df in dataframes.items():

    possible_date_columns = [
        column
        for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in [
                "date",
                "time",
                "created",
                "updated",
                "timestamp"
            ]
        )
    ]

    print(
        f"{table_name}: "
        f"{possible_date_columns}"
    )

bengaluru_civic_complaints: ['created_at']
citizen_complaints: []
emergency_detection: []
enterprise_department_priority: ['timestamp', 'sentiment_score', 'resolution_time_hrs', 'sentiment_label']
government_schemes_lookup: []
government_sentiment: ['sentiment', 'timestamp']
harmful_content: []
manual_health_education: []

In [20]:
for table_name, df in dataframes.items():

    possible_date_columns = [
        column
        for column in df.columns
        if any(
            keyword in column.lower()
            for keyword in [
                "date",
                "created_at",
                "updated_at",
                "timestamp"
            ]
        )
    ]

    for column in possible_date_columns:

        converted = pd.to_datetime(
            df[column],
            errors="coerce"
        )

        successful_conversion = converted.notna().mean()

        if successful_conversion >= 0.60:
            df[column] = converted

            print(
                f"Converted {table_name}.{column} "
                f"to datetime"
            )

    dataframes[table_name] = df

Converted government_sentiment.timestamp to datetime

In [21]:
cleaning_summary = []

for table_name, df in dataframes.items():

    cleaning_summary.append({
        "table_name": table_name,
        "rows": len(df),
        "columns": len(df.columns),
        "missing_values": int(df.isna().sum().sum()),
        "duplicate_rows": int(df.duplicated().sum())
    })

cleaning_summary = pd.DataFrame(cleaning_summary)

cleaning_summary

,table_name,rows,columns,missing_values,duplicate_rows
0,bengaluru_civic_complaints,16040,18,8579,0
1,citizen_complaints,10196,6,6541,0
2,emergency_detection,7613,6,2595,0
3,enterprise_department_priority,100000,19,5155,0
4,government_schemes_lookup,3397,11,42,0
5,government_sentiment,60201,11,0,0
6,harmful_content,5852,6,0,0
7,manual_health_education,100,6,0,0

In [22]:
for table_name, df in dataframes.items():

    print("\n" + table_name.upper())

    for column in df.columns:
        print(f" - {column}")

BENGALURU_CIVIC_COMPLAINTS
 - sql_row_id
 - created_at
 - ward_id
 - title
 - description
 - sub_category_id
 - civic_agency_id
 - location
 - address
 - latitude
 - longitude
 - ward_title
 - category_id
 - category_title
 - sub_category_title
 - civic_agency_title
 - complaint_status_title
 - comment_count

CITIZEN_COMPLAINTS
 - sql_row_id
 - tweet_id
 - tweet_text
 - c_and_g
 - category
 - organization

EMERGENCY_DETECTION
 - sql_row_id
 - id
 - keyword
 - location
 - text
 - target

ENTERPRISE_DEPARTMENT_PRIORITY
 - sql_row_id
 - interaction_id
 - citizen_id
 - timestamp
 - channel
 - department
 - scheme_name
 - priority
 - state
 - language
 - sentiment_score
 - resolution_time_hrs
 - reopen_count
 - escalated
 - satisfaction_rating
 - cost_to_resolve_inr
 - complexity_index
 - sentiment_label
 - interaction_summary

GOVERNMENT_SCHEMES_LOOKUP
 - sql_row_id
 - scheme_name
 - slug
 - details
 - benefits
 - eligibility
 - application
 - documents
 - level
 - schemecategory
 - tags

GOVERNMENT_SENTIMENT
 - sql_row_id
 - source_type
 - record_id
 - text_content
 - sentiment
 - user_or_category
 - organization
 - complaint_and_grievance_flag
 - timestamp
 - likes
 - retweets

HARMFUL_CONTENT
 - sql_row_id
 - text_id
 - text
 - task_1
 - task_2
 - task_3

MANUAL_HEALTH_EDUCATION
 - sql_row_id
 - manual_id
 - text
 - complaint_reason
 - department
 - feedback_category

In [23]:
cleaned_folder = "cleaned_csv_files"

os.makedirs(
    cleaned_folder,
    exist_ok=True
)

for table_name, df in dataframes.items():

    output_path = os.path.join(
        cleaned_folder,
        f"{table_name}_cleaned.csv"
    )

    df.to_csv(
        output_path,
        index=False
    )

    print(f"Saved: {output_path}")

Saved: cleaned_csv_files\bengaluru_civic_complaints_cleaned.csv
Saved: cleaned_csv_files\citizen_complaints_cleaned.csv
Saved: cleaned_csv_files\emergency_detection_cleaned.csv
Saved: cleaned_csv_files\enterprise_department_priority_cleaned.csv
Saved: cleaned_csv_files\government_schemes_lookup_cleaned.csv
Saved: cleaned_csv_files\government_sentiment_cleaned.csv
Saved: cleaned_csv_files\harmful_content_cleaned.csv
Saved: cleaned_csv_files\manual_health_education_cleaned.csv

In [24]:
from sqlalchemy import create_engine
from sqlalchemy import text
from urllib.parse import quote_plus

In [25]:
mysql_username = "root"
mysql_password = "Kishore@6741"
mysql_host = "localhost"
mysql_port = "3306"

database_name = "government_analytics"

In [26]:
encoded_password = quote_plus(mysql_password)

print(encoded_password)

Kishore%406741

In [27]:
server_engine = create_engine(
    f"mysql+mysqlconnector://{mysql_username}:{encoded_password}@{mysql_host}:{mysql_port}/"
)

print("Connection object created.")

Connection object created.

In [28]:
try:
    with server_engine.connect() as conn:
        version = conn.execute(text("SELECT VERSION();"))
        print(version.scalar())

except Exception as e:
    print(e)

8.0.46

In [29]:
with server_engine.begin() as conn:
    conn.execute(
        text("""
        CREATE DATABASE IF NOT EXISTS government_analytics;
        """)
    )

print("Database created successfully.")

Database created successfully.

In [30]:
database_engine = create_engine(
    f"mysql+mysqlconnector://{mysql_username}:{encoded_password}@{mysql_host}:{mysql_port}/{database_name}"
)

print("Connected to government_analytics")

Connected to government_analytics

In [31]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\nagis\SocialIQ project
['.ipynb_checkpoints', 'bengaluru_civic_complaints.csv', 'citizen_complaints.csv.csv', 'cleaned_csv_files', 'dataset_summary_before_cleaning.csv', 'emergency_detection.csv', 'enterprise_department_priority.csv', 'Government_Project_SQL_Implementation.ipynb', 'government_schemes_lookup.csv', 'government_sentiment.csv', 'harmful_content.csv', 'manual_health_education.csv']

In [32]:
import pandas as pd

bengaluru_df = pd.read_csv(
    "bengaluru_civic_complaints.csv",
    low_memory=False
)

print("File loaded successfully")
print("Rows:", bengaluru_df.shape[0])
print("Columns:", bengaluru_df.shape[1])

bengaluru_df.head()

File loaded successfully
Rows: 16073
Columns: 22

,created_at,ward_id,title,description,sub_category_id,civic_agency_id,location,address,latitude,longitude,ward_title,category_id,category_title,sub_category_title,civic_agency_title,complaint_status_title,comment_count,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,01-01-2019 06:33,22.0,Govt Road is encroached with knowledge of offi...,Govt Road is encroached by Private buildings i...,162,10,"9Th Cross St, Hanumanthappa Layout, Sultanpaly...",Opposite S M Food Palace,13.0318055,77.6054367,Vishwanath Nagenahalli,382,Community Infrastructure and Services,Government Land/Property Encroachment,BBMP,Resolved,6,NaN,NaN,NaN,NaN,NaN
1,01-01-2019 09:59,27.0,S,Money menace is a huge problem with residents ...,42,NaN,"2, 1St Cross Rd, Chikka Banaswadi, Ombr Layout...",NaN,13.0065056,77.6444845,Banasavadi,9,Others,Others,NaN,Open,0,NaN,NaN,NaN,NaN,NaN
2,01-01-2019 12:57,17.0,Showing old owner name in online property tax ...,My property SAS base app no 1600800634 New Pid...,148,10,"No.18 19Th Cross, 19, 19Th Cross, Muthyala Nag...",J P Park,13.0386344,77.551505,J P Park,1,Certificates,Property Tax,BBMP,Resolved,1,NaN,NaN,NaN,NaN,NaN
3,01-01-2019 13:09,161.0,Extremely dangerous BTP barrier in the middle ...,Extremely dangerous BTP barrier in the middle ...,67,10,"Anjaneya Nagar, Ittamadu, Banashankari 3Rd Sta...",NaN,12.9268712,77.5447143,Hosakerehalli,15,"Mobility - Roads, Footpaths and Infrastructure",Tarring Or Asphalting Of Existing Road,BBMP,Resolved,2,NaN,NaN,NaN,NaN,NaN
4,01-01-2019 14:41,176.0,No water supply,Lat few days there is no proper water supply i...,182,2,"27Th Main Rd, Btm 2Nd Stage, Kuvempu Nagar, St...",27th main btm 2nd stage,12.9139053,77.6142494,BTM Layout,23,Water Supply and Services,Regular Water Supply,BWSSB,Open,0,NaN,NaN,NaN,NaN,NaN

In [33]:
bengaluru_df.columns.tolist()

['created_at',
 'ward_id',
 'title',
 'description',
 'sub_category_id',
 'civic_agency_id',
 'location',
 'address',
 'latitude',
 'longitude',
 'ward_title',
 'category_id',
 'category_title',
 'sub_category_title',
 'civic_agency_title',
 'complaint_status_title',
 'comment_count',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21']

In [34]:
bengaluru_df = bengaluru_df.loc[
    :,
    ~bengaluru_df.columns.str.startswith("Unnamed")
]

print("Unwanted columns removed")
print("Remaining columns:", bengaluru_df.shape[1])

Unwanted columns removed
Remaining columns: 17

In [35]:
import re

def clean_column_name(column_name):
    column_name = str(column_name)
    column_name = column_name.strip()
    column_name = column_name.lower()
    column_name = re.sub(r"[^a-z0-9_]+", "_", column_name)
    column_name = re.sub(r"_+", "_", column_name)
    column_name = column_name.strip("_")
    return column_name

bengaluru_df.columns = [
    clean_column_name(column)
    for column in bengaluru_df.columns
]

print(bengaluru_df.columns.tolist())

['created_at', 'ward_id', 'title', 'description', 'sub_category_id', 'civic_agency_id', 'location', 'address', 'latitude', 'longitude', 'ward_title', 'category_id', 'category_title', 'sub_category_title', 'civic_agency_title', 'complaint_status_title', 'comment_count']

In [42]:
import re

def clean_column_name(column_name):
    column_name = str(column_name).strip().lower()
    column_name = re.sub(r"[^a-zA-Z0-9_]+", "_", column_name)
    column_name = re.sub(r"_+", "_", column_name)
    return column_name.strip("_")


bengaluru_df.columns = [
    clean_column_name(column)
    for column in bengaluru_df.columns
]

bengaluru_df.columns.tolist()

['created_at',
 'ward_id',
 'title',
 'description',
 'sub_category_id',
 'civic_agency_id',
 'location',
 'address',
 'latitude',
 'longitude',
 'ward_title',
 'category_id',
 'category_title',
 'sub_category_title',
 'civic_agency_title',
 'complaint_status_title',
 'comment_count']

In [43]:
before_rows = len(bengaluru_df)

bengaluru_df = bengaluru_df.dropna(
    axis=0,
    how="all"
)

after_rows = len(bengaluru_df)

print("Rows before:", before_rows)
print("Rows after:", after_rows)

Rows before: 16073
Rows after: 16073

In [44]:
duplicate_count = bengaluru_df.duplicated().sum()

print("Duplicate rows found:", duplicate_count)

bengaluru_df = bengaluru_df.drop_duplicates().reset_index(
    drop=True
)

print("Duplicate rows removed")

Duplicate rows found: 33
Duplicate rows removed

In [45]:
if "sql_row_id" in bengaluru_df.columns:
    bengaluru_df = bengaluru_df.drop(
        columns=["sql_row_id"]
    )

bengaluru_df.insert(
    0,
    "sql_row_id",
    range(1, len(bengaluru_df) + 1)
)

bengaluru_df.head()

,sql_row_id,created_at,ward_id,title,description,sub_category_id,civic_agency_id,location,address,latitude,longitude,ward_title,category_id,category_title,sub_category_title,civic_agency_title,complaint_status_title,comment_count
0,1,01-01-2019 06:33,22.0,Govt Road is encroached with knowledge of offi...,Govt Road is encroached by Private buildings i...,162,10,"9Th Cross St, Hanumanthappa Layout, Sultanpaly...",Opposite S M Food Palace,13.0318055,77.6054367,Vishwanath Nagenahalli,382,Community Infrastructure and Services,Government Land/Property Encroachment,BBMP,Resolved,6
1,2,01-01-2019 09:59,27.0,S,Money menace is a huge problem with residents ...,42,NaN,"2, 1St Cross Rd, Chikka Banaswadi, Ombr Layout...",NaN,13.0065056,77.6444845,Banasavadi,9,Others,Others,NaN,Open,0
2,3,01-01-2019 12:57,17.0,Showing old owner name in online property tax ...,My property SAS base app no 1600800634 New Pid...,148,10,"No.18 19Th Cross, 19, 19Th Cross, Muthyala Nag...",J P Park,13.0386344,77.551505,J P Park,1,Certificates,Property Tax,BBMP,Resolved,1
3,4,01-01-2019 13:09,161.0,Extremely dangerous BTP barrier in the middle ...,Extremely dangerous BTP barrier in the middle ...,67,10,"Anjaneya Nagar, Ittamadu, Banashankari 3Rd Sta...",NaN,12.9268712,77.5447143,Hosakerehalli,15,"Mobility - Roads, Footpaths and Infrastructure",Tarring Or Asphalting Of Existing Road,BBMP,Resolved,2
4,5,01-01-2019 14:41,176.0,No water supply,Lat few days there is no proper water supply i...,182,2,"27Th Main Rd, Btm 2Nd Stage, Kuvempu Nagar, St...",27th main btm 2nd stage,12.9139053,77.6142494,BTM Layout,23,Water Supply and Services,Regular Water Supply,BWSSB,Open,0

In [46]:
database_engine

Engine(mysql+mysqlconnector://root:***@localhost:3306/government_analytics)

In [47]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

mysql_username = "root"
mysql_password = "Kishore@6741"
mysql_host = "localhost"
mysql_port = "3306"
database_name = "government_analytics"

encoded_password = quote_plus(mysql_password)

database_engine = create_engine(
    f"mysql+mysqlconnector://"
    f"{mysql_username}:{encoded_password}"
    f"@{mysql_host}:{mysql_port}/"
    f"{database_name}"
)

print("Database engine created")

Database engine created

In [48]:
from sqlalchemy import text

try:
    with database_engine.connect() as connection:
        result = connection.execute(
            text("SELECT DATABASE();")
        )

        print("Connected database:", result.scalar())

except Exception as error:
    print("Connection failed")
    print(error)

Connected database: government_analytics

In [49]:
try:
    bengaluru_df.to_sql(
        name="bengaluru_civic_complaints",
        con=database_engine,
        if_exists="replace",
        index=False,
        chunksize=500
    )

    print("Table uploaded successfully")

except Exception as error:
    print("Upload failed")
    print(error)

Table uploaded successfully

In [50]:
if_exists="replace"

In [52]:
query = """
SELECT COUNT(*) AS total_rows
FROM bengaluru_civic_complaints;
"""

row_count = pd.read_sql(
    query,
    database_engine
)

row_count

   total_rows
0       16040

In [53]:
python_rows = len(bengaluru_df)

query = """
SELECT COUNT(*) AS mysql_rows
FROM bengaluru_civic_complaints;
"""

mysql_result = pd.read_sql(
    query,
    database_engine
)

mysql_rows = int(mysql_result.loc[0, "mysql_rows"])

print("Python rows:", python_rows)
print("MySQL rows:", mysql_rows)

if python_rows == mysql_rows:
    print("Success: All rows were uploaded")
else:
    print("Warning: Row counts do not match")

Python rows: 16040
MySQL rows: 16040
Success: All rows were uploaded

In [54]:
import os
import re
import glob
import getpass
import pandas as pd

from sqlalchemy import create_engine, text
from urllib.parse import quote_plus

mysql_username = "root"
mysql_host = "localhost"
mysql_port = "3306"
database_name = "government_analytics"

mysql_password = getpass.getpass("Enter MySQL password: ")
encoded_password = quote_plus(mysql_password)

file_patterns = {
    "bengaluru_civic_complaints": "bengaluru_civic_complaints*.csv",
    "citizen_complaints": "citizen_complaints*.csv",
    "emergency_detection": "emergency_detection*.csv",
    "enterprise_department_priority": "enterprise_department_priority*.csv",
    "government_schemes_lookup": "government_schemes_lookup*.csv",
    "government_sentiment": "government_sentiment*.csv",
    "harmful_content": "harmful_content*.csv",
    "manual_health_education": "manual_health_education*.csv"
}

current_folder = os.getcwd()

def find_file(pattern):
    matches = glob.glob(os.path.join(current_folder, pattern))
    matches = [
        file for file in matches
        if "_cleaned" not in os.path.basename(file).lower()
    ]

    if not matches:
        return None

    matches.sort(key=os.path.getmtime, reverse=True)
    return matches[0]

def clean_column_name(column):
    column = str(column).strip().lower()
    column = re.sub(r"[^a-z0-9_]+", "_", column)
    column = re.sub(r"_+", "_", column)
    column = column.strip("_")

    if not column:
        column = "column"

    if column[0].isdigit():
        column = "col_" + column

    return column

def make_unique_columns(columns):
    counts = {}
    result = []

    for column in columns:
        if column not in counts:
            counts[column] = 1
            result.append(column)
        else:
            counts[column] += 1
            result.append(f"{column}_{counts[column]}")

    return result

def load_csv(file_path):
    encodings = ["utf-8", "utf-8-sig", "latin-1", "cp1252"]

    for encoding in encodings:
        try:
            return pd.read_csv(
                file_path,
                encoding=encoding,
                low_memory=False
            )
        except UnicodeDecodeError:
            continue

    raise ValueError(f"Unable to read {file_path}")

resolved_files = {}

for table_name, pattern in file_patterns.items():
    file_path = find_file(pattern)

    if file_path is None:
        raise FileNotFoundError(
            f"File not found for {table_name}. "
            f"Place it in: {current_folder}"
        )

    resolved_files[table_name] = file_path
    print(table_name, ":", os.path.basename(file_path))

dataframes = {}

for table_name, file_path in resolved_files.items():
    df = load_csv(file_path)

    df.columns = df.columns.astype(str)

    df = df.loc[
        :,
        ~df.columns.str.strip().str.lower().str.startswith("unnamed")
    ]

    df = df.dropna(axis=0, how="all")
    df = df.dropna(axis=1, how="all")

    cleaned_columns = [
        clean_column_name(column)
        for column in df.columns
    ]

    df.columns = make_unique_columns(cleaned_columns)

    text_columns = df.select_dtypes(
        include=["object", "string"]
    ).columns

    for column in text_columns:
        df[column] = (
            df[column]
            .astype("string")
            .str.strip()
        )

    df = df.replace(
        [
            "",
            " ",
            "null",
            "NULL",
            "None",
            "none",
            "NaN",
            "nan",
            "N/A",
            "NA"
        ],
        pd.NA
    )

    df = df.drop_duplicates().reset_index(drop=True)

    if "sql_row_id" in df.columns:
        df = df.drop(columns=["sql_row_id"])

    df.insert(
        0,
        "sql_row_id",
        range(1, len(df) + 1)
    )

    dataframes[table_name] = df

    print(
        table_name,
        "cleaned:",
        len(df),
        "rows and",
        len(df.columns),
        "columns"
    )

server_engine = create_engine(
    f"mysql+mysqlconnector://"
    f"{mysql_username}:{encoded_password}"
    f"@{mysql_host}:{mysql_port}/",
    pool_pre_ping=True
)

with server_engine.connect() as connection:
    version = connection.execute(
        text("SELECT VERSION();")
    ).scalar()

    print("Connected to MySQL:", version)

with server_engine.begin() as connection:
    connection.execute(
        text(
            f"""
            CREATE DATABASE IF NOT EXISTS `{database_name}`
            CHARACTER SET utf8mb4
            COLLATE utf8mb4_unicode_ci
            """
        )
    )

database_engine = create_engine(
    f"mysql+mysqlconnector://"
    f"{mysql_username}:{encoded_password}"
    f"@{mysql_host}:{mysql_port}/"
    f"{database_name}",
    pool_pre_ping=True
)

for table_name, df in dataframes.items():
    print("Uploading:", table_name)

    df.to_sql(
        name=table_name,
        con=database_engine,
        if_exists="replace",
        index=False,
        chunksize=500
    )

    print(table_name, "uploaded successfully")

verification = []

for table_name, df in dataframes.items():
    with database_engine.connect() as connection:
        mysql_rows = connection.execute(
            text(
                f"""
                SELECT COUNT(*)
                FROM `{table_name}`
                """
            )
        ).scalar()

    verification.append({
        "table_name": table_name,
        "python_rows": len(df),
        "mysql_rows": int(mysql_rows),
        "rows_match": len(df) == int(mysql_rows)
    })

verification_df = pd.DataFrame(verification)

print("\nUpload verification:")
print(verification_df.to_string(index=False))

print("\nAll tables:")
print(
    pd.read_sql(
        "SHOW TABLES;",
        database_engine
    ).to_string(index=False)
)

database_engine.dispose()
server_engine.dispose()

print("\nCompleted successfully.")

Enter MySQL password:  ········

bengaluru_civic_complaints : bengaluru_civic_complaints.csv
citizen_complaints : citizen_complaints.csv.csv
emergency_detection : emergency_detection.csv
enterprise_department_priority : enterprise_department_priority.csv
government_schemes_lookup : government_schemes_lookup.csv
government_sentiment : government_sentiment.csv
harmful_content : harmful_content.csv
manual_health_education : manual_health_education.csv
bengaluru_civic_complaints cleaned: 16040 rows and 18 columns
citizen_complaints cleaned: 10196 rows and 6 columns
emergency_detection cleaned: 7613 rows and 6 columns
enterprise_department_priority cleaned: 100000 rows and 19 columns
government_schemes_lookup cleaned: 3397 rows and 11 columns
government_sentiment cleaned: 60201 rows and 11 columns
harmful_content cleaned: 5852 rows and 6 columns
manual_health_education cleaned: 100 rows and 6 columns
Connected to MySQL: 8.0.46
Uploading: bengaluru_civic_complaints
bengaluru_civic_complaints uploaded successfully
Uploading: citizen_complaints
citizen_complaints uploaded successfully
Uploading: emergency_detection
emergency_detection uploaded successfully
Uploading: enterprise_department_priority
enterprise_department_priority uploaded successfully
Uploading: government_schemes_lookup
government_schemes_lookup uploaded successfully
Uploading: government_sentiment
government_sentiment uploaded successfully
Uploading: harmful_content
harmful_content uploaded successfully
Uploading: manual_health_education
manual_health_education uploaded successfully

Upload verification:
                    table_name  python_rows  mysql_rows  rows_match
    bengaluru_civic_complaints        16040       16040        True
            citizen_complaints        10196       10196        True
           emergency_detection         7613        7613        True
enterprise_department_priority       100000      100000        True
     government_schemes_lookup         3397        3397        True
          government_sentiment        60201       60201        True
               harmful_content         5852        5852        True
       manual_health_education          100         100        True

All tables:
Tables_in_government_analytics
    bengaluru_civic_complaints
            citizen_complaints
           emergency_detection
enterprise_department_priority
     government_schemes_lookup
          government_sentiment
               harmful_content
       manual_health_education

Completed successfully.